### ISSUE TITLE
Issue and Pull Request Templates

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/.github#4]
- [ ] Create a folder `Templates` in the root to store templates mentioned below.
- [x] Create `issue.md`, a markdown file containing a template which will be used further to create issues on our repositories.
- [ ] Create `pullrequest.md` a markdown file containing a template which will be used further to create pull requests on our repositories.
- [ ] Create a `README.md` in the root folder to highlight these templates to be a standard followed throughout the Organization.

If contributing internally, create a branch linking this issue and make a pull request to main. Otherwise fork and raise a pull request.

**Comment by ChinmayAlekar** [comment]
Hey @vish-rt can I work on this issue?

**Comment by vish-rt** [comment]
> Hey @vish-rt ,can I work on this issue?

Hi! We need someone with experience in contributing to the Organization with our internal workflow to write this. @demonkillerr has insisted on contributing to this issue.

Feel free to check back in the future in another repository!
